name: Build ZMK firmware
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "keymap-drawer/**"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@2a9ac3ba7f23fe96938bcf36059fb25e6a73e4ae
